In [387]:
import pandas as pd
import numpy as np

In [388]:
base_treino = pd.read_csv('C:/Users/gmore/deep/titanic/train.csv')
base_teste =  pd.read_csv('C:/Users/gmore/deep/titanic/test.csv')

In [389]:
base_treino.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [390]:
base_teste.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [391]:
base_treino.shape

(891, 12)

In [392]:
base_teste.shape

(418, 11)

In [393]:
x_teste = base_teste

In [394]:
x_teste.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [396]:
idade_media_teste = x_teste['Age'].mean()
tarifa_media_teste = x_teste['Fare'].mean()
x_teste.update(x_teste['Age'].fillna(idade_media_teste))
x_teste.update(x_teste['Cabin'].fillna('Sem Registro'))
x_teste.update(x_teste['Fare'].fillna(tarifa_media_teste))

In [397]:
x_teste.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [398]:
x = base_treino.drop(['Survived', 'Cabin'], axis = 1)

In [399]:
y = base_treino['Survived']

In [400]:
x.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Embarked         2
dtype: int64

In [401]:
print(x.Embarked.value_counts())

S    644
C    168
Q     77
Name: Embarked, dtype: int64


In [404]:
idade_media = x['Age'].mean()
x.update(x['Age'].fillna(idade_media))
x.update(x['Embarked'].fillna('S'))

In [405]:
x.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [407]:
x

PassengerId  Pclass                                               Name  \
0              1       3                            Braund, Mr. Owen Harris   
1              2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2              3       3                             Heikkinen, Miss. Laina   
3              4       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)   
4              5       3                           Allen, Mr. William Henry   
5              6       3                                   Moran, Mr. James   
6              7       1                            McCarthy, Mr. Timothy J   
7              8       3                     Palsson, Master. Gosta Leonard   
8              9       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)   
9             10       2                Nasser, Mrs. Nicholas (Adele Achem)   
10            11       3                    Sandstrom, Miss. Marguerite Rut   
11            12       1                           Bonnell, Miss. Elizabeth   
12            13       3                     Saundercock, Mr. William Henry   
13            14       3                        Andersson, Mr. Anders Johan   
14            15       3               Vestrom, Miss. Hulda Amanda Adolfina   
15            16       2                   Hewlett, Mrs. (Mary D Kingcome)    
16            17       3                               Rice, Master. Eugene   
17            18       2                       Williams, Mr. Charles Eugene   
18            19       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...   
19            20       3                            Masselmani, Mrs. Fatima   
20            21       2                               Fynney, Mr. Joseph J   
21            22       2                              Beesley, Mr. Lawrence   
22            23       3                        McGowan, Miss. Anna "Annie"   
23            24       1                       Sloper, Mr. William Thompson   
24            25       3                      Palsson, Miss. Torborg Danira   
25            26       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...   
26            27       3                            Emir, Mr. Farred Chehab   
27            28       1                     Fortune, Mr. Charles Alexander   
28            29       3                      O'Dwyer, Miss. Ellen "Nellie"   
29            30       3                                Todoroff, Mr. Lalio   
..           ...     ...                                                ...   
861          862       2                        Giles, Mr. Frederick Edward   
862          863       1  Swift, Mrs. Frederick Joel (Margaret Welles Ba...   
863          864       3                  Sage, Miss. Dorothy Edith "Dolly"   
864          865       2                             Gill, Mr. John William   
865          866       2                           Bystrom, Mrs. (Karolina)   
866          867       2                       Duran y More, Miss. Asuncion   
867          868       1               Roebling, Mr. Washington Augustus II   
868          869       3                        van Melkebeke, Mr. Philemon   
869          870       3                    Johnson, Master. Harold Theodor   
870          871       3                                  Balkic, Mr. Cerin   
871          872       1   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)   
872          873       1                           Carlsson, Mr. Frans Olof   
873          874       3                        Vander Cruyssen, Mr. Victor   
874          875       2              Abelson, Mrs. Samuel (Hannah Wizosky)   
875          876       3                   Najib, Miss. Adele Kiamie "Jane"   
876          877       3                      Gustafsson, Mr. Alfred Ossian   
877          878       3                               Petroff, Mr. Nedelio   
878          879       3                                 Laleff, Mr. Kristo   
879          880       1      Potter, Mrs. Thomas Jr (L

In [408]:
y.isnull().sum()

0

In [409]:
import tensorflow as tf
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [410]:
x.columns

Index(['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch',
       'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [411]:
nome_colunas_categoricas = ['Sex', 'Name', 'Ticket', 'Embarked']

In [412]:
colunas_categoricas = [tf.feature_column.categorical_column_with_vocabulary_list(key = c, vocabulary_list=x[c].unique()) for c in nome_colunas_categoricas]

In [413]:
nome_colunas_numericas = ['PassengerId', 'Pclass', 'Age', 'SibSp', 'Parch', 'Fare']

In [414]:
colunas_numericas = [ tf.feature_column.numeric_column(key = c) for c in nome_colunas_numericas ]

In [415]:
colunas = colunas_categoricas + colunas_numericas

In [416]:
x_treinamento = x
y_treinamento = y

In [417]:
y_treinamento.shape

(891,)

In [418]:
x_teste.shape

(418, 11)

In [419]:
y_teste = y_treinamento[0:418,]

In [420]:
y_teste.shape

(418,)

In [423]:
funcao_treinamento = tf.estimator.inputs.pandas_input_fn(x = x_treinamento, y = y_treinamento,
                                                        batch_size = 32, num_epochs = None, shuffle = True)

In [424]:
classificador = tf.estimator.LinearClassifier(feature_columns=colunas)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\gmore\\AppData\\Local\\Temp\\tmpfm571atp', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [425]:
classificador.train(input_fn=funcao_treinamento, steps = 10000)

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\gmore\AppData\Local\Temp\tmpfm571atp\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 22.18071, step = 1
INFO:tensorflow:global_step/sec: 150.011
INFO:tensorflow:loss = 5.0377955, step = 101 (0.671 sec)
INFO:tensorflow:global_step/sec: 328.999
INFO:tensorflow:loss = 8.018097, step = 201 (0.302 sec)
INFO:tensorflow:global_step/sec: 298.553
INFO:tensorflow:loss = 9.23045, step = 301 (0.340 sec)
INFO:tensorflow:global_step/sec: 285.758
INFO:tensorflow:loss = 8.677118, step = 401 (0.353 sec)
INFO:tensorflow:global_step/sec: 295.904
INFO:tensorflow:loss = 6.034807, step =

INFO:tensorflow:global_step/sec: 279.372
INFO:tensorflow:loss = 0.34234214, step = 7901 (0.354 sec)
INFO:tensorflow:global_step/sec: 272.522
INFO:tensorflow:loss = 0.5429276, step = 8001 (0.369 sec)
INFO:tensorflow:global_step/sec: 284.135
INFO:tensorflow:loss = 0.36311936, step = 8101 (0.351 sec)
INFO:tensorflow:global_step/sec: 256.45
INFO:tensorflow:loss = 0.43756706, step = 8201 (0.392 sec)
INFO:tensorflow:global_step/sec: 274.015
INFO:tensorflow:loss = 0.38997334, step = 8301 (0.365 sec)
INFO:tensorflow:global_step/sec: 275.849
INFO:tensorflow:loss = 0.40688986, step = 8401 (0.362 sec)
INFO:tensorflow:global_step/sec: 260.456
INFO:tensorflow:loss = 0.34474757, step = 8501 (0.381 sec)
INFO:tensorflow:global_step/sec: 308.686
INFO:tensorflow:loss = 0.46503484, step = 8601 (0.326 sec)
INFO:tensorflow:global_step/sec: 263.202
INFO:tensorflow:loss = 0.36085716, step = 8701 (0.378 sec)
INFO:tensorflow:global_step/sec: 290.742
INFO:tensorflow:loss = 0.28545892, step = 8801 (0.343 sec)
IN

In [426]:
funcao_previsao = tf.estimator.inputs.pandas_input_fn(x = x_teste, batch_size = 32, shuffle = False)

In [427]:
previsoes = classificador.predict(input_fn=funcao_previsao)

In [428]:
previsoes_final = []
for p in classificador.predict(input_fn=funcao_previsao):
    previsoes_final.append(p['class_ids'])

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\gmore\AppData\Local\Temp\tmpfm571atp\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.


In [429]:
previsoes_final

[array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([0], dtype=int64),
 array([1], dtype=int64),
 array([1], dtype=int64),
 array([0], 

In [431]:
from sklearn.metrics import accuracy_score
taxa_acerto = accuracy_score(y_teste, previsoes_final)
taxa_acerto

0.5095693779904307